#+TITLE: Practical intro to Probability theory.

* Course name: Практическое введение в теорию вероятностей :RUS:

* Ideas
  - VK post length (log-normal)
  - letter frequencies in a text -- text as random letters
  - quality control -- 2𝛔 deviation in real-time to detect production line failures.

* Цели                                                                  :RUS:
  * показать и по возможности дать интуицию: почему и как строятся
    математические модели связанные со случайными событиями;
  * обсудить примеры, какими бывают такие модели (про разные случайные величины
    и разные вопросы, на которые можно отвечать с их помощью);
  * упомянуть ключевые понятия и дать соответствующую интуицию -- так, чтобы в
    будущем студент (1) не воспринимал предмет как что-то сложное и непонятное,
    и (2) легче ориентировался в материале, если решит взять полный курс по
    теорверу.
  * личные задачи: 
    - объяснить относительно сложные понятия (мат. ожидание, дисперсия,
      независимость событий и случайных величин) на основе численных примеров и
      интуиции, без масштабного привлечения мат. анализа.
    - хотя бы частично выстроить курс вокруг "численных" примеров (на Python)

* Аннтоация / Summary :RUS:
  Когда мы подбрасываем монетку, делаем тест на COVID или получаем вариант
  контрольной -- мы сталкиваемся со случайностями. Но как они устроены? Как их
  описать? Можно ли смоделировать длину поста "ВКонтакте" как случайную
  величину? А художественный текст -- как случайный набор букв? В основе ответов
  на эти вопросы лежит теория вероятностей. Мы обсудим основные идеи на примерах
  (кое-где, на Python), но без погружения в доказательства. Для 9-11 классов,
  специальной подготовки не нужно.

* Course outline
** Intro [10 min]
   - COVID test; defects detection; elections or DNA sequences -- what's random?
   - need to know how randomness works;
   - probs appears when something is unknown, and usually within data science-y tasks
     (including stuff from ML, statistics, data mining and other)
   - Our course = (1) practical intro to (2) probs theory
     + theory -- reg math. Prob space, independence, random vars and how to describe these.
     + practice -- short intro, hence examples (incl. Python instead of proofs)
   - no special requirements besides maybe algebra. Python is good, but not necessary.
     Need interest in math and modeling, though.
   - after the course:
     + general feeling about the structure
     + some mathematical intuition
     + feeling that when you have randomness, quite often you can design a model that
       will give a practically valuable answer, or advise. It might require some work,
       but there is nothing "sacred" in it. It can, and should be done.
** As uploaded to the base
  - *1 день:* *Модель для случайных событий.:* Классическое определение
    вероятности, частоты, эксперименты с кубиками. Смещенные кубики;
    вероятностное пространство. Исходы, события, независимые события. Элементы
    теории множеств.
  - *2 день:* Условная вероятность. COVID-тест как случайное событие. Ошибки 1 и
    2 рода.
  - *3 день:* Случайные *величины*-1, и как их описывать (дискретный случай).
    Распределение. Математическое ожидание, дисперсия. Параметры распределения
    vs. выборочные оценки.
  - *4 день:* Случайные *величины*-2: как обобщить на непрерывный случай?
    Функция распределения, плотность вероятности (численный пример). Зависимость
    и корреляция.
  - *5 день:* Дополнительные примеры, оставшиеся вопросы и проч. (если останется
    время -- конечно, "оценка гипотез").

** Day 1. A model for random events [60 min]
    - Some key questions
    - Interpretations, frequencies.
    - rolling a dice -- *num example*. Classical definition of prob.
    - probability space: outcomes, events, probs.
    - independent events; very intro notes in set theory.

** Day 2. Conditional probability and friends. [60 min]
   - Conditional probability -- intuition, definition.
   - Bayes' formula.
   - Confusion matrix, COVID test as a random variable, I and II type errors.
   - Hopefully, testing hypotheses (for simple, discrete case).

** Days 3. Random variables: discrete case. [60 min]
   - Intuition, definition, examples.
   - Discrete case:
     + How to describe these: prob mass functions.
     + Moments and friends: expectation, variance.
     + Model parameters vs. "statistics" (sample functions)!

** Day 4. Random variables: continuous case. [60 min]
   - Generalizations needed: zero density at every point.
   - Cumulative density function.
   - Probability density function.
   - Calculating the expectation (numerical example).

** Day 5. More examples, Q&A, revising key points as necessary. [60 min]

* Further readings
